### PR TITLE
standardizing dot github files

### PR DESCRIPTION
**Pull request by mateodelnorte**

### CODE REVIEW

**Comment by mateodelnorte** [comment]
@aleclarson renovate seems to not be pulling in updated deps for our child repos, although it's working for https://github.com/mateodelnorte/meta. `meta-project` should be referencing https://github.com/mateodelnorte/meta-exec/releases/tag/v1.4.0 now but is still on 0.0.0. 

Any idea?

**Comment by aleclarson** [comment]
Probably because caret ranges are being used in this package

**Comment by mateodelnorte** [comment]
I was thinking that might be it, as well. I can try and pin it to a not-latest version and see if it issues an update PR.

**Comment by mateodelnorte** [comment]
Yup. That did the trick. 👍

**Pull request merged**
