### PR TITLE
refactor: improve dx

### PR DESCRIPTION
**Pull request by aleclarson**
- improved log messages
- load .meta before creating directory
- resolve `dest` relative to .meta before adding to "projects" object
- use `tildify` to improve readability of file paths in console
- use `chalk` to pretty things up
- skip "git init" when a .git directory already exists
- do a "git pull" for new directories
- update remote origin even if already set
- do nothing if project exists and it uses the given origin
- use `get-meta-file` to load .meta
- remove unused dependencies

Merge this _after_ #9

### CODE REVIEW

**Comment by aleclarson** [comment]
This depends on a PR to `meta-exec` that I'll submit shortly.

**Comment by aleclarson** [comment]
In response to https://github.com/mateodelnorte/meta/issues/87#issuecomment-448625581, I think we could add a `--no-pull` for those edge cases. And eventually a `config.project.noPull` setting in the `.meta` module (to set `--no-pull` as the default behavior).

**Comment by aleclarson** [comment]
Imgur

**Comment by aleclarson** [comment]
@mateodelnorte Friendly ping 😄

**Comment by aleclarson** [comment]
Note to self: Implement a CLI flag for shallow cloning at some point.

**Comment by mateodelnorte** [comment]
hrm. wonder why this still has the conflict.

**Comment by aleclarson** [comment]
Forgot to rebase before regenerating the lockfile. 😅

**Pull request merged**
